steps:
   # Clone a public repo and write its revision to a VERSION file.
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    git clone https://github.com/alvarohernandezrad/CI-CD-Benchmarking
    
- name: 'docker/compose:1.19.0'
  args: ['-f', 'CI-CD-Benchmarking/web-app/docker-compose.yml', 'up', '-d']

- name: 'gcr.io/cloud-builders/docker'
  args: ['logs', 'docker-node-mongo']

- name: 'gcr.io/cloud-builders/docker'
  args: ['exec', 'docker-node-mongo', 'curl', 'http://localhost:3000']

- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    curl http://localhost:3000
