steps:
# CI
# Clone repository
- name: 'gcr.io/cloud-builders/git'
  id: 'Clone repositories'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    git clone https://github.com/adeiarias/CI-CD-Benchmarking.git
